services:
  - type: web
    name: servidor-webhooks
    rootDirectory: servidor_webhooks
    env: python
    pythonVersion: 3.10
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"